const ec2data = [
  {
    ResourceId: "i-0a12b34c56d78e901",
    ResourceName: "EC2-Production-Server",
    Region: "us-east-1",
    Status: "Running",
  },
  {
    ResourceId: "spn-aws-compute-usage-001",
    ResourceName: "Compute Savings Plan",
    Region: "us-east-1",
    Status: "Active",
  },
  {
    ResourceId: "db-01rds-primary",
    ResourceName: "RDS-Primary-DB",
    Region: "us-east-1",
    Status: "Available",
  },
  {
    ResourceId: "db-01rds-replica",
    ResourceName: "RDS-Replica",
    Region: "us-east-1",
    Status: "Available",
  },
  {
    ResourceId: "arn:aws:ecs:us-east-1:292569186237:service/pof/pof-service",
    ResourceName: "POF-ECS-Service",
    Region: "us-east-1",
    Status: "Active",
  },
  {
    ResourceId: "arn:aws:ecs:us-east-1:292569186237:service/pof/pof-service",
    ResourceName: "POF-ECS-Service",
    Region: "us-east-1",
    Status: "Active",
  },
  {
    ResourceId: "arn:aws:ecs:us-east-1:292569186237:service/pof/pof-service",
    ResourceName: "POF-ECS-Service",
    Region: "us-east-1",
    Status: "Running",
  },
  {
    ResourceId: "arn:aws:ecs:us-east-1:292569186237:service/pof/pof-service",
    ResourceName: "POF-ECS-Service",
    Region: "us-east-1",
    Status: "Running",
  },
  {
    ResourceId: "arn:aws:ecs:us-east-1:292569186237:service/pof/pof-service",
    ResourceName: "POF-ECS-Service",
    Region: "us-east-1",
    Status: "Draining",
  },
  {
    ResourceId: "rds-db-12345",
    ResourceName: "DB-Service-A",
    Region: "us-east-1",
    Status: "Available",
  },
  {
    ResourceId: "rds-db-67890",
    ResourceName: "DB-Service-B",
    Region: "us-east-1",
    Status: "Stopped",
  },
  {
    ResourceId: "i-0c98f76b54d32a101",
    ResourceName: "EC2-Analytics-Node",
    Region: "us-east-1",
    Status: "Running",
  },
];

const rdsData = [
  {
    ResourceId: "db-01rds-primary",
    ResourceName: "RDS-Primary-DB",
    Region: "us-east-1",
    Status: "Available",
    Engine: "MySQL",
    InstanceClass: "db.t3.medium",
  },
  {
    ResourceId: "db-02rds-replica",
    ResourceName: "RDS-Replica",
    Region: "us-west-2",
    Status: "Available",
    Engine: "PostgreSQL",
    InstanceClass: "db.r5.large",
  },
  {
    ResourceId: "db-03rds-backup",
    ResourceName: "RDS-Backup-DB",
    Region: "eu-west-1",
    Status: "Stopped",
    Engine: "MySQL",
    InstanceClass: "db.t3.small",
  },
   {
    ResourceId: "db-01rds-primary",
    ResourceName: "RDS-Primary-DB",
    Region: "us-east-1",
    Status: "Available",
    Engine: "MySQL",
    InstanceClass: "db.t3.medium",
  },
  {
    ResourceId: "db-02rds-replica",
    ResourceName: "RDS-Replica",
    Region: "us-west-2",
    Status: "Available",
    Engine: "PostgreSQL",
    InstanceClass: "db.r5.large",
  },
  {
    ResourceId: "db-03rds-backup",
    ResourceName: "RDS-Backup-DB",
    Region: "eu-west-1",
    Status: "Stopped",
    Engine: "MySQL",
    InstanceClass: "db.t3.small",
  },
];

const asgData = [
  {
    ResourceId: "asg-web-servers-001",
    ResourceName: "Web-Servers-ASG",
    Region: "us-east-1",
    Status: "Active",
    MinSize: "2",
    MaxSize: "10",
  },
  {
    ResourceId: "asg-api-servers-002",
    ResourceName: "API-Servers-ASG",
    Region: "us-west-2",
    Status: "Active",
    MinSize: "1",
    MaxSize: "5",
  },
  {
    ResourceId: "asg-worker-nodes-003",
    ResourceName: "Worker-Nodes-ASG",
    Region: "eu-west-1",
    Status: "Inactive",
    MinSize: "0",
    MaxSize: "8",
  },
    {
    ResourceId: "asg-api-servers-002",
    ResourceName: "API-Servers-ASG",
    Region: "us-west-2",
    Status: "Active",
    MinSize: "1",
    MaxSize: "5",
  },
  {
    ResourceId: "asg-worker-nodes-003",
    ResourceName: "Worker-Nodes-ASG",
    Region: "eu-west-1",
    Status: "Inactive",
    MinSize: "0",
    MaxSize: "8",
  },,  {
    ResourceId: "asg-api-servers-002",
    ResourceName: "API-Servers-ASG",
    Region: "us-west-2",
    Status: "Active",
    MinSize: "1",
    MaxSize: "5",
  },
  {
    ResourceId: "asg-worker-nodes-003",
    ResourceName: "Worker-Nodes-ASG",
    Region: "eu-west-1",
    Status: "Inactive",
    MinSize: "0",
    MaxSize: "8",
  },
];

export { ec2data, rdsData, asgData };